### ISSUE TITLE
geo.event.actionwheel doesn't include wheel delta

### ISSUE THREAD

**Issue by sgratzl** [OpenGeoscience/geojs#1024]
I tried to use the `geo.event.actionwheel` to capture the mouse wheel event. However, the event doesn't provide the `deltaX` and `deltaY` information as provided by the MouseWheel event (https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent)

**Comment by manthey** [comment]
The action events are abstract events that are generated from other events.  Does the `geo.event.pan` event contain the information you need?

**Comment by sgratzl** [comment]
No, cause I'm not looking for the shifted delta when moving the view but the mouse wheel delta. So, how much the user rotated the mouse wheel and in which direction.

**Comment by manthey** [comment]
@sgratzl The action wheel event was intended to expose this data, but there was a bug that prevented it (fix in #1030).

**Comment by sgratzl** [comment]
thx
