### ISSUE TITLE
Hammer is not handled as an optional dependency

### ISSUE THREAD

**Issue by subdavis** [OpenGeoscience/geojs#1056]
After checking the docs for `optionalDependency` [on npm](https://docs.npmjs.com/files/package.json#optionaldependencies) I don't think hammerjs is being handled properly.

When I install with `--ignore-optional`, hammerjs is not included. 

```js
this.geoViewer.interactor().options(interactorOpts);
```

This causes:

```
Uncaught TypeError: Hammer.Manager is not a constructor
    at mapInteractor._connectEvents (geo.lean.js?7edf:23359)
    at mapInteractor.options (geo.lean.js?7edf:23430)
    at VueComponent.baseInit (annotator.js?1b77:81)
    at VueComponent.init (ImageAnnotator.vue?9ffc:34)
    at Image.img.onload (ImageAnnotator.vue?9ffc:27)
```

I think the missing hammer dependency isn't being handled correctly.  Here's __webpack_require:

```js
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
```

When the module isn't loaded but the dependency is listed as optional, no error is thrown by `__webpack_require` and the value of `Hammer` is `{}` and *not* `undefined`.

This is in `_connectEvents`

**Comment by subdavis** [comment]
A bit of extra info:  It looks like a bug in webpack?!

This error is thrown on the second call, not the first, when __webpack_require hits the installedModules cache where the value of exports is `{}`.

I don't really know what to make of that.

**Comment by manthey** [comment]
Do you think it is worth guarding this sort of issue in GeoJS?  Specifically, for Hammer, we could test if it is not undefined AND `Hammer.Manager` (or some other expected element) is defined.  This would be done for other optional modules, too.

**Comment by manthey** [comment]
Alternately, do we need to add documentation somewhere to point to https://webpack.js.org/configuration/output/#outputstrictmoduleexceptionhandling?

**Comment by subdavis** [comment]
> add documentation somewhere to point to https://webpack.js.org/configuration/output/#outputstrictmoduleexceptionhandling?

I think that's really all that is needed here.
