### ISSUE TITLE
Trasparent tile layer issue

### ISSUE THREAD

**Issue by rbrundritt** [OpenGeoscience/geojs#1069]
I'm overlaying a couple of tile layers on the map. One is semi-transparent (i.e. layer layer above an imagery layer). What I am noticing is that the semi transparent layer is being rendered multiple times on the map (looks like three levels, possible previous, current and next zoom level?), and this is causing issues as I end up with overlapping labels. Here is a screenshot:

![image](https://user-images.githubusercontent.com/6459716/92974261-a9118680-f43a-11ea-8501-5b161fb18c80.png)

I have a sample live here: https://azuremapscodesamples.azurewebsites.net/Third%20Party%20Map%20Controls/Raster%20tiles%20in%20GeoJS.html

**Comment by manthey** [comment]
There is an option for layers whether all lower levels of tiles should be rendered or not.  On non-transparent layers, have all lower levels of tiles gives the perception of better updates when panning.  On transparent layers, it is undesirable.  This option can be changed on the tile layer.  See the `keepLower` option (https://opengeoscience.github.io/geojs/apidocs/geo.tileLayer.html#.spec).
