### ISSUE TITLE
Add custom headers to tile requests

### ISSUE THREAD

**Issue by rbrundritt** [OpenGeoscience/geojs#1071]
I'm trying to connect to a secure tile server that requires passing authentication details in the header of each tile request. I can't for the life of me find any way to append customer header values to the tile requests.

**Comment by manthey** [comment]
I think you'd need to override the `fetch` method of the `imageTile` class to do this.  It uses an HTMLImageElement to fetch the actual tile (see `src/imageTile.js`).

HTMLImageElement doesn't support setting custom headers.  I think you'd have to switch to fetching the image via an XMLHttpRequest where you can set headers, and, once that returns, set the HTMLImageElement's src to a URL.createObjectURL of the returned data.

**Comment by rbrundritt** [comment]
Thanks. I managed to figure out how to get this working. In my case I'm leveraging osmLayer, and need to override the _getTile function. I'm going to create a new class that extends the osmLayer and overrides this function so that I don't change how the osmLayer works when used normally.
