### ISSUE TITLE
Tiled pixelmaps

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#1113]
Add support for tiled pixelmaps.

Also, we may want to render pixelmap borders (rather than just fills) -- though this might be better as a separate PR.

**Comment by jeffbaumes** [comment]
Maybe for the short term borders can just be "burned in" to the image using a special value (black?) when desired. In theory the borders could just be another region of pixels that could be mapped to a color for rendering just like all the other regions, although you don't want borders to be selectable.

**Comment by manthey** [comment]
Definitely that works as a pixelmap; each border could be a distinct value just like each superpixel is a distinct value; then you'd have control over the color of individual borders (and know which border the cursor is over, etc.).

**Comment by manthey** [comment]
This was added in #1153.
