### ISSUE TITLE
Broken links to source code of examples

### ISSUE THREAD

**Issue by jamesscottbrown** [OpenGeoscience/geojs#1168]
The examples (e.g. the [Hurricanes example](https://opengeoscience.github.io/geojs/examples/hurricanes/)) have a "Source code" link in the footer, but these links are broken.

[Looking in the `gh-pages` branch](https://github.com/OpenGeoscience/geojs/tree/gh-pages/examples/hurricanes/docs), the `main.html` file that should be inside `geojs/examples/hurricanes/docs/` is in fact inside the nested subdirectories `home/runner/work/geojs/geojs/examples/hurricanes/` inside that directory.

**Comment by manthey** [comment]
Thanks for reporting this.
