### ISSUE TITLE
getError performance issue

### ISSUE THREAD

**Issue by jeffbaumes** [OpenGeoscience/geojs#1174]
When looking into possible performance issues while panning and zooming, I came across this:

![image](https://user-images.githubusercontent.com/81305/152585958-21b8eeb0-fb6e-4db0-8259-a298e12e9833.png)

It seems getError from _renderImageQuads, which apparently is checking for out of memory errors, is taking up about 60% of the time. In some longer frames it takes up even more (here 95%):

![image](https://user-images.githubusercontent.com/81305/152586206-0ef49f11-4d41-47ff-9dfc-159d22a31268.png)

I found this documentation stating why it's so slow.

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#avoid_blocking_api_calls_in_production

Should this check be removed?

Note this is from looking at this example:

https://demo.kitware.com/histomicstk/#item/61fc3f6c3ac19d243a3f32e9

**Comment by manthey** [comment]
The check was added because a user had a memory issue that was not at all apparent -- just losing the context.  Probably it could be changed to only check after we try to load a texture that is larger in pixels than any texture we've loaded before which should balance the desire for checking with performance.

**Comment by jeffbaumes** [comment]
That could work. It seems in the example I was trying, it was hitting that check all the time. I notice for example [here](https://opengeoscience.github.io/geojs/examples/color-legend/) it does not seem to hit that check at all, must be the tile size in the histomics example is larger.

**Comment by manthey** [comment]
The version of geojs on demo.kitware.com is probably older AND therefore hitting the check all the time rather than only for large textures, whereas the version deployed from github is current master and therefore only checks if the texture is over 4k^2.

**Comment by jeffbaumes** [comment]
Ah ok, so basically it's a solved issue, thanks. Sorry for the noise!
