### ISSUE TITLE
Implement sticky for GL layers

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#156]

**Comment by aashish24** [comment]
@manthey I think we are still missing this for GL layers? Not a priority just checking.

**Comment by manthey** [comment]
We only have it for d3 renderer layers (so not for GL or canvas renderer layers).  I'll also note that you *must* set the sticky property when you create the layer; it would be straightforward to make it settable.

**Comment by manthey** [comment]
This can be done manually through the position accessors.
