### ISSUE TITLE
GL plane feature does not respect GCS

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#175]

**Comment by manthey** [comment]
Did you have a specific example where this occurs?  It may be fixed in PR #410.

**Comment by jbeezley** [comment]
I think this is still an issue.  At least, that is how I interpreted your comments here: https://github.com/OpenGeoscience/geojs/blob/master/src/gl/planeFeature.js#L51

**Comment by manthey** [comment]
Yes.  It may be handy to be able to specify the interface gcs on a feature (or at least on this feature), as the tile layer has the data in the map gcs and it would be wasteful to convert it to the interface gcs only to have it converted back again.

**Comment by manthey** [comment]
Fixed in PR #480.
