### ISSUE TITLE
Support marker clustering

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#180]
This is more of a long term goal to keep in mind.  I just came across a [leaflet plugin](https://github.com/Leaflet/Leaflet.markercluster) that github uses to render geojson files.  It does point cluster with animations like [this](http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html).  It is a really nice effect that I was trying to get working with the early GRITS prototype.  It would be especially useful to display large numbers of features with svg.  The plugin claims it works well with up to 50000 points.

**Comment by jbeezley** [comment]
The API exists since #414.  Improvements still necessary:
 - [ ] Only render the points visible in the viewport
 - [ ] Animate splitting the clusters (#386)
 - [ ] Add text labels (#352)

**Comment by manthey** [comment]
Animations can be done after #386.  Closing for now.
