### ISSUE TITLE
Support generic tile provider URL's

### ISSUE THREAD

**Issue by mwoehlke-kitware** [OpenGeoscience/geojs#279]
Right now, GeoJS defaults to using the basic OSM tile server. In many cases, it is desirable to use other tile servers. While there appears to be partial support for this by specifying the 'baseUrl' when creating a map layer, it would be much better if GeoJS instead took the "standard" format tile URL's that are often provided on map servers' sites.

Examples:

    'http://{s}.tilecdn.example.com/terrain/{z}/{x}/{y}.png'
    'http://example.com/tiles.cgi?user=name&apikey=secret&x={x}&y={y}&zoom={z}'

Support for subdomains in addition to x,y,z would also be useful. (Note: subdomains are the '{s}' parameter; the idea is to rotate tile requests through the available subdomains, which should default to 'a', 'b' and 'c'.)

**Comment by aashish24** [comment]
:+1: right. we also talked about abstracting OSM code as well to make it more general.

**Comment by mwoehlke-kitware** [comment]
Other than this, it looks to me like the current implementation is already "general", as much as most similar tools, anyway... except for the name, of course. There may not be very much to do as far as 'making it more general'.

**Comment by jbeezley** [comment]
Implemented in #361.
