### ISSUE TITLE
Tile zoom level selection has issues

### ISSUE THREAD

**Issue by mwoehlke-kitware** [OpenGeoscience/geojs#284]
The tile zoom level selected for OSM maps... just seems screwy. Besides that there is never a 1:1 zoom (such that maps *always* look blurry compared to other map modules that *only* show 1:1 zoom), the zoom level selection seems to be dependent on unknown factors, probably including window size. In some cases the selected zoom level can even be just plain wrong, i.e. selecting a lower level when a higher level would still be larger than 1:1. In other cases, higher zoom level tiles can be used long after they are being downsamples past legibility.

Leaflet (correct: tiles are zoomed 1:1):
![map-leaflet](https://cloud.githubusercontent.com/assets/6474409/5651749/14d2d666-9678-11e4-94b2-9424e7584e15.png)

GeoJS (incorrect: is zoomed in (slightly) *more* than Leaflet example but is using a lower tile zoom level):
![map-geojs](https://cloud.githubusercontent.com/assets/6474409/5651748/14d2a3c6-9678-11e4-9b34-3b47b706a07f.png)

(These are close to (but slightly smaller than) the browser window size.)

**Comment by jbeezley** [comment]
Also noted in https://github.com/OpenGeoscience/geojs/issues/54.

**Comment by jbeezley** [comment]
Fixed in #318.
