### ISSUE TITLE
The default resize assumes starting position at 0, 0

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#296]
@jbeezley please delete this issue if this is a dupllicate.

**Comment by jbeezley** [comment]
No, thanks for adding it.  I almost forgot.

**Comment by jbeezley** [comment]
I don't recall what this was about, but resizing works completely differently now.  Feel free to reopen and clarify the issue if it is still relevant.

**Comment by aashish24** [comment]
@jbeezley I don't remember it exactly but I believe the issue was when we have apps using center other then 0,0, the code would still consider center to be at 0,0, and hence resize will result in wrong location. I agree that if we encounter the same problem, we can create a new issue for it.
