### ISSUE TITLE
Warn user when when GL is not available

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#312]

**Comment by jbeezley** [comment]
Even better, fallback to a different renderer when possible.

**Comment by aashish24** [comment]
+1

**Comment by manthey** [comment]
Someone mentioned that there was some problem with detecting WebGL reliably.  Does anyone remember the details?  This stackoverflow issue shows how others have done it: http://stackoverflow.com/questions/11871077/proper-way-to-detect-webgl-support

Should there be a function in vgl? Or should this be solely in geojs?

**Comment by jbeezley** [comment]
We could probably copy the [Modernizr code](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/webgl/extensions.js).  I could go either way with where to put it.  I suppose in VGL would make the most sense because it is only place where webgl API is actually touched.   I can see an API inside geojs that allows the user to probe which renderers are available in the current environment which would be more general than querying for WebGL (i.e. we could allow for loading geojs without vgl or d3).

**Comment by manthey** [comment]
Added in PR #502.
