### ISSUE TITLE
Update readthedocs by adding a high level description of the project.

### ISSUE THREAD

**Issue by jcfr** [OpenGeoscience/geojs#322]
See http://geojs.readthedocs.org/en/latest/

Text from this article could be re-used ? See http://www.kitware.com/source/home/post/152

**Comment by jbeezley** [comment]
Ironically enough, I was just working on some long overdue [updates](https://github.com/OpenGeoscience/geojs/tree/rtd-updates) to the readthedocs page yesterday.  I should have something ready soon.

**Comment by jcfr** [comment]
:+1:  Looking good.

**Comment by jbeezley** [comment]
Thanks for the note.  Fixed in #323.
