### ISSUE TITLE
layerEvents example broken

### ISSUE THREAD

**Issue by jeffbaumes** [OpenGeoscience/geojs#327]
If you click "add top layer" then "remove top layer", you no longer see any interaction behavior with the two boxes. Also, the "add top layer" button no longer functions.

http://opengeoscience.github.io/geojs/examples/layerEvents/

**Comment by jbeezley** [comment]
I'll get to this at some point, but for now I have removed the link from the main examples page.

**Comment by jbeezley** [comment]
This was actually fixed a while back, I just needed to update the geojs source on the gh-pages branch.
