### ISSUE TITLE
Collect performance data with testing

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#334]
@manthey has been hard at work making performance improvements to the GL features.  Because this is really the *raison d'être* of GeoJS, I think we should start collecting this kind of information to show improvements and regressions over time.  I had the thought to push tests to [jsperf](http://jsperf.com/), but it would be even better to create some infrastructure (possibly using [benchmarkjs](http://benchmarkjs.com/)) to collect this data along with the nightly testing on a variety of hosts.  We should look into this along with our new buildbot infrastructure.

**Comment by jeffbaumes** [comment]
+2, 1 for the idea, 1 for the use of French

**Comment by jbeezley** [comment]
Tout à fait!

**Comment by aashish24** [comment]
:laughing: :+1: I guess now I have to learn french in order to work on GeoJS

**Comment by aashish24** [comment]
@manthey I will follow up with CMake folks regarding this.

**Comment by manthey** [comment]
This is now being collected on cdash via PR #543.
