### ISSUE TITLE
If dynamic draw then directly manipulate the buffers 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#335]

**Comment by jbeezley** [comment]
@manthey This has been done right?

**Comment by manthey** [comment]
Yes.

On Thu, Jun 11, 2015 at 12:51 PM, Jonathan Beezley <notifications@github.com
> wrote:

> @manthey <https://github.com/manthey> This has been done right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGeoscience/geojs/issues/335#issuecomment-111204781>
> .
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439
