### ISSUE TITLE
Provide consistent meta for interaction events

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#348]
pan event provides screenDelta but zoom event does not (which means that developers have to compute it)

**Comment by aashish24** [comment]
#237

**Comment by aashish24** [comment]
May be map should also fire pan event?

**Comment by jbeezley** [comment]
What screen delta do you need?  For pan events, the screen delta is the number of pixels the center is shifted by.  Since #299, the zoom event no longer modifies the map center.  Instead it fires a secondary pan event after the zoom is finished to recenter about the mouse pointer.
