### ISSUE TITLE
Implement parallel projection and option for discreet zoom

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#362]
Currently, we only support perspective and continuous zoom.

**Comment by aashish24** [comment]
I will update the vgl code to handle this case. @ronichoudhury and I will work on it. It would be nice to sign off on this feature. Looking forward to it.

**Comment by ronichoudhury** [comment]
:+1:

**Comment by zachmullen** [comment]
:+1: How hard is this to change? I am looking through the code but can't find where I can easily hook into the projection matrix.

**Comment by aashish24** [comment]
@zachmullen it will be partially in VGL and rest in GeoJS. Look into vglRenderer (but I am modifying that heavily as part of my enable_multilayer_gl branch. Are you offering help :smile: ?

**Comment by zachmullen** [comment]
I am offering help if it isn't a great deal of work... it looks as though calling `enableParallelProjection(true)` on the camera object will do the job, I just need to find out where in geoJS I can access the camera object.

**Comment by aashish24** [comment]
Cool! Just wondering what project you are using GeoJS for? I think I may need to provide some insight before you dig into it. Also, you will need my other branch merged in as it has significant changes w.r.t. GL.

**Comment by zachmullen** [comment]
I was looking into it for the sake of XDATA currently, and was just curious to see if this would be easy. I was able to get ahold and set the projection to parallel using

    var camera = mapObj.renderer().contextRenderer().camera();
    camera.enableParallelProjection(true);
    camera.setParallelProjection(0, width, height, 0);


However, as one might expect this broke most interaction. I will wait for now until your vgl branch lands.

**Comment by aashish24** [comment]
Right. I would wait on this until next week. Would it be possible to help with some other task in the mean time?

**Comment by zachmullen** [comment]
Sure, though I still do not know much about the code base :)

**Comment by aashish24** [comment]
Another good one would be this: https://github.com/OpenGeoscience/geojs/issues/375

Such feature will be immensely useful right away.

**Comment by aashish24** [comment]
Assigning it to @manthey. I will provide help if needed.

**Comment by manthey** [comment]
Added in PR #421.
