### ISSUE TITLE
documentation/source files for individual prereqs

### ISSUE THREAD

**Issue by ronichoudhury** [OpenGeoscience/geojs#366]
It would be good to know how to reconstruct the JS requirements for geo.js for the following reasons:
- if I am already using, e.g., d3, it becomes tough to use geo.ext.min.js because it will cause d3 to load again, etc.
- if I am not using some feature of geojs that is dependent on one of the requirements, I can choose to skip it

**Comment by aashish24** [comment]
+1

**Comment by jbeezley** [comment]
http://geojs.readthedocs.org/en/latest/users.html#dependencies
