### ISSUE TITLE
Add support for non-rectangular tiles

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#374]

**Comment by jbeezley** [comment]
Are you thinking hexagonal tiles?

**Comment by ronichoudhury** [comment]
+:cat: for hex tiles

**Comment by manthey** [comment]
If by this we just mean quads, it will be covered along with issue #228.

**Comment by aashish24** [comment]
@manthey I was thinking quads, this was something needed for polar projection tiles.

**Comment by manthey** [comment]
Arbitrary quadrangles are supported via PR #528.  If we ever want non-quadrangle tiles, we should make a new feature request.
