### ISSUE TITLE
Add choropleth layer

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#375]
This layer will make it easy to create choropleth map
Should take a geojson that defines the boundaries

**Comment by manthey** [comment]
This could be a derivative or special case of the contour feature, which would allow it to use the same color range options that are already implemented there.  My understanding is that, instead of a square grid, you have a set of polygons, each with a single scalar value.

**Comment by aashish24** [comment]
@manthey yup.. thats pretty much the idea and in this case the code / shader will be much simpler I think.

**Comment by aashish24** [comment]
@jbeezley here is what I mentioend earlier: Jenks Natural Breaks and Quantize choropleth scaling is what we will need for choropleth feature (It should be a feature and not a layer as referred earlier).

**Comment by dcjohnston** [comment]
Sorry if this is a naive question, but where does natural breaks algorithm fall into this? Since the polygon feature defines the boundaries, and we use some scaling algorithm to determine the color for each feature based on a scalar property, I'm not understanding where we'd need to use it.

**Comment by manthey** [comment]
The natural breaks algorithm is one choice of a function that converts the
scalar value to color.  Other libraries have a variety of choices for this
conversion: quantile coloring, equal interval, standard deviations, natural
breaks.  I think we will want to be able to specify a method for color
scaling, and include a small set of standard functions within the core
library.  This will allow a user to add their own function or use one of
these standards without an additional library.

On Wed, Aug 19, 2015 at 4:58 PM, Derek Connor Johnston <
notifications@github.com> wrote:

> Sorry if this is a naive question, but where does natural breaks algorithm
> fall into this? Since the polygon feature defines the boundaries, and we
> use some scaling algorithm to determine the color for each feature based on
> a scalar property, I'm not understanding where we'd need to use it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGeoscience/geojs/issues/375#issuecomment-132781607>
> .
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by jbeezley** [comment]
In addition to what @manthey said, my strategy has been to take algorithms like this and implement them in a generic utility function first.  This has the benefit of making it possible to test the core algorithm independent of the rest of the library as well as use the algorithm in other places as necessary.  For example, see [clustering.js](https://github.com/OpenGeoscience/geojs/blob/master/src/util/clustering.js) and [pointFeature.js](https://github.com/OpenGeoscience/geojs/blob/master/src/core/pointFeature.js#L79) .

**Comment by aashish24** [comment]
@jbeezley I will add @dcjohnston to the developers list (or you can). After talking to @nicopresto, we thought that it would be nice if @dcjohnston can implement this in GeoJS.

**Comment by jbeezley** [comment]
@aashish24 @dcjohnston Invitation sent.

**Comment by aashish24** [comment]
@dcjohnston welcome to the team!! :tada:

**Comment by dcjohnston** [comment]
Im excited to be here @aashish24 ! I've got the choropleth layer working more or less, but I'm running into performance issues with multipolygons. I've written the choropleth feature as essentially a wrapper that will handle the color scaling and then create appropriate polygon features with the processed data. With multipolygons, I'm basically running a map over feature.geometry.coordinates (accoding to geojson spec, each element in this array is a single polygon, which checks out). However, I'm not sure if there are simply too many polygons being created, or if there is a better piece of the API for handling multipolygons  (maybe vgl.geomtryData ? ), but the rendering of the choropleth is too slow with multipolygons. What's the best way to get multipolygons on the map?

**Comment by aashish24** [comment]
#433
