### ISSUE TITLE
Better defaults for points in jQuery widget

### ISSUE THREAD

**Issue by jeffbaumes** [OpenGeoscience/geojs#390]
Current defaults look pretty bad, perhaps use gray or light blue with thin gray border, a bit smaller?

![screen shot 2015-05-08 at 11 15 30 am](https://cloud.githubusercontent.com/assets/81305/7539241/a85dd4f8-f573-11e4-85ca-29cd3975f289.png)

**Comment by aashish24** [comment]
+1. I will push a fix..

**Comment by aashish24** [comment]
I am proposing to use the colors as generally defaulted to by other GIS packages. Its typically a shade of orange (see here: http://dev.openlayers.org/examples/regular-polygons.html).

**Comment by jbeezley** [comment]
That would be okay for polygons.  I'm not sure about for points though.

**Comment by aashish24** [comment]
@jbeezley you can try the points in the same code as well. The reason behind orange / shade of yellow is it stand outs better for most of the tiles out there. Blue is not good as it is typically the color of the water and and for other tiles.

**Comment by jeffbaumes** [comment]
The orange / darker orange looks better than red / green. I'll take anything :) Can we also support semi-transparent fill in the default?

**Comment by jbeezley** [comment]
Here is what @aashish24 came up with as an alternative.  http://jsbin.com/tikota/2/edit?output

**Comment by aashish24** [comment]
@jeffbaumes I was thinking transparency as like in the example. I will push a new commit for tests and opacity.

**Comment by jeffbaumes** [comment]
I also think a bit smaller would be good - maybe 50-75% of the size.

**Comment by aashish24** [comment]
Currently that's 4 pixel. Anything less than that would be too small? Is it possible that jquery plugin's default is something else @jbeezley ?

**Comment by aashish24** [comment]
I take it back..its 8 pixel dia. I intended it to be 4 pixel dia.

**Comment by jbeezley** [comment]
Yes, the jquery plugin uses the point feature default.  This is what 4 looks like: http://jsbin.com/tikota/5/edit?js,output

I think 5 or 6 would be best.

**Comment by aashish24** [comment]
Okay.. I picked 5. Also, I set it to transparent as well. Some tests are failing but it looks like we found some bug.

**Comment by jbeezley** [comment]
Done in #392.
