### ISSUE TITLE
Z values don't plot properly on gl features

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#394]
If you have a non-zero z value, it doesn't plot where you would expect on the map projection.  There is something wrong with either the model view matrix or the projection matrix.  It seems to also engage the clipping in some instances where it shouldn't.

**Comment by aashish24** [comment]
@manthey were you using point feature or line? Just wanted to make sure that I can replicate this and add a test for it once I have a fix. It may be that it exists for all the features.

**Comment by manthey** [comment]
I encountered it in the polygon feature.  I also happens in the contour
feature using the same matrices.

I assume that there is an issue with one of the matrix calculations, but
didn't hunt it down.

On Mon, Jun 22, 2015 at 9:43 AM, Aashish Chaudhary <notifications@github.com
> wrote:

> @manthey <https://github.com/manthey> were you using point feature or
> line? Just wanted to make sure that I can replicate this and add a test for
> it once I have a fix. It may be that it exists for all the features.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGeoscience/geojs/issues/394#issuecomment-114108670>
> .
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by manthey** [comment]
I deliberately ignore the z value in the contour feature, so if you fix
this, we should change that, too.

On Mon, Jun 22, 2015 at 9:52 AM, David Manthey <david.manthey@kitware.com>
wrote:

> I encountered it in the polygon feature.  I also happens in the contour
> feature using the same matrices.
>
> I assume that there is an issue with one of the matrix calculations, but
> didn't hunt it down.
>
> On Mon, Jun 22, 2015 at 9:43 AM, Aashish Chaudhary <
> notifications@github.com> wrote:
>
>> @manthey <https://github.com/manthey> were you using point feature or
>> line? Just wanted to make sure that I can replicate this and add a test for
>> it once I have a fix. It may be that it exists for all the features.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpenGeoscience/geojs/issues/394#issuecomment-114108670>
>> .
>>
>
>
>
> --
> David Manthey
> R&D Engineer
> Kitware Inc.
> (518) 881-4439
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by aashish24** [comment]
@zachmullen this would be good bug to work on.

**Comment by manthey** [comment]
As an update to this (after PR #410), we expect z-coordinates to be from 0 to 1 in all renderers.  We may want to add a default transform for z coordinates (much as we have a default transform for map coordinates), or at least investigate a proj4 compatible way to specify such a scaling.

**Comment by aashish24** [comment]
@manthey it may not be true for 3d renderer via cesium sinxe there the z would be in spherical coordinates. Lets talk more about it next week, 

Thanks

**Comment by aashish24** [comment]
@manthey I do not remember if this is still a valid issue?

**Comment by manthey** [comment]
Yes, it is.

In some features (and in non-GL renderers), we ignore the z value.  We *don't* do this in all features (we should until we implement 3D-aware features).  For instance, I know we don't ignore the z value in the contour feature (and possibly others, but I didn't check).
