### ISSUE TITLE
Replace selenium tests with headless-gl

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#405]
It looks like it was exceedingly difficult to get working, but [mapbox](https://github.com/mapbox/mapbox-gl-js) has figured out to get headless webgl working on travis executed purely in node (or iojs).  We should be able to copy their setup scripts to do the same and replace the awful selenium tests with a more standard node testing framework.

**Comment by aashish24** [comment]
Nice!

**Comment by manthey** [comment]
This has been started (using xvfb, not headless-gl) in PR #651.

**Comment by manthey** [comment]
Done in PR #677.
