### ISSUE TITLE
Consider using ES6 (EMCA6) feature using Babel 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#418]
This is a low priority item but we should plan on doing this in next 2-3 months. At that time it would be good to discuss class design in GeoJS.

**Comment by zachmullen** [comment]
Now that it's 3 years later, I think this has become more important -- using modern language features can drastically improve the development experience. At least, I would vote to prioritize this, especially since it's so easy to support this from where geojs is right now.

**Comment by manthey** [comment]
I hacked this into a development environment, and the only issue I saw was with jQuery global usage (so addressing #862 would make this trivial).
