### ISSUE TITLE
JSON reader renders polygons as lines

### ISSUE THREAD

**Issue by danlamanna** [OpenGeoscience/geojs#435]
Seen [here](https://github.com/OpenGeoscience/geojs/blob/master/src/core/jsonReader.js#L186)

@aashish24

**Comment by aashish24** [comment]
@dcjohnston care to fix this bug?

**Comment by dcjohnston** [comment]
Sure thing, probably won't be able to touch until this tomorrow at the earliest, most likely Monday.

**Comment by aashish24** [comment]
Thanks, that sounds fine to me. Also specially since this is sort of related to the awesome work you have done recently.

**Comment by dcjohnston** [comment]
Submitted PR.
