### ISSUE TITLE
Add ability to rotate the map (orthogonal to view direction) 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#442]

**Comment by manthey** [comment]
@aashish24, @jbeezley: When we have a rotated camera (and, in the future, a tilted camera), what would you expect camera().bounds to return?

Since it is an object with left, top, right, bottom, I imagine that it would be the 2-D bounding box in the internal map coordinate system that covers the visible area.  This has the virtue that we would then fetch tiles that cover the visible area, even if we get too many of them.

Alternately, it could be the four corners of the screen at altitude 0 as a set of four points.  For compatibility, it could have left, top, right, bottom as the 2-D bounding box and the four corners under other properties (ul, ur, ll, lr)? (upperLeft, upperRight, lowerLeft, lowerRight)? (topLeft, topRight, bottomLeft, bottomRight)?

Or it could be eight points defining the frustum of the visible space...

Opinions?

**Comment by jbeezley** [comment]
My original intent was to have the `left`, `right`, `bottom`, and `top` mean the maximum extent of the visible bounds in world coordinates.  My plan was always to just load everything inside these bounds and optimize later.

What these values mean in 2.5 or 3D, I have no idea.  Maybe now is the correct time to start worrying about it.

**Comment by aashish24** [comment]
> Since it is an object with left, top, right, bottom, I imagine that it would be the 2-D bounding box in the internal map coordinate system that covers the visible area. This has the virtue that we would then fetch tiles that cover the visible area, even if we get too many of them.

It would be axis (or world) align bounding box if I understand what you are saying here I believe that's what @jbeezley is saying as well.

**Comment by aashish24** [comment]
> Or it could be eight points defining the frustum of the visible space...

I would construct a 2d box that covers the viewable region and then I will move the planes such that they fit the geometry contained in that viewable volume (if we have any 3D). We shoudl have another api to get the frustrum.

**Comment by manthey** [comment]
I have other interface questions.  I assume that if you zoom or pan, the rotation should stay the same.

What should you see if we are clamping the zoom?  Allow the same zoom levels as the unrotated map?  Or allow zooming out until opposite corners are visible on the display?

What should you see if we are clamping the X or Y bounds?

If a program sets `camera.bounds` (frequently with the output from `boundsFromZoomAndCenter`), there will need to be an option about whether to undo the rotation or not.

**Comment by aashish24** [comment]
> I have other interface questions. I assume that if you zoom or pan, the rotation should stay the same.

agree

> What should you see if we are clamping the zoom? Allow the same zoom levels as the unrotated map? Or allow zooming out until opposite corners are visible on the display?

Opposite corners are visible on the display. It will be important to display that portion of data sometimes. From technical point of view, you are still clamping on the bounds it's just that now the bounds are bigger because of the rotation. This would be something we will need to bio-imaging.

**Comment by manthey** [comment]
Fundamentally, we have baked in a lot of assumptions about how we present the map.  Currently, the map's view is determined by two values: `zoom` and `center`.

It will be most straightforward to add `rotation` to this, and, when we want tilted maps, to add some sort of tilt property.

Our camera class supports generic 3-D view matrices, but the map class does not.  I think modifying the map class to have a generic 3-D view is more work than it is worth at this time, so, unless there are objections, I'll add rotations and another parameter, and defer making a generic 3-D map view matrix for a later project, if it is ever desired.

**Comment by jbeezley** [comment]
I agree, the map class, feature classes, and even the conventions used in events would need major work to support generic 3D operations.  Let's leave that for when (or if) it's actually needed.

**Comment by aashish24** [comment]
> I think modifying the map class to have a generic 3-D view is more work than it is worth at this time, so, unless there are objections, I'll add rotations and another parameter, and defer making a generic 3-D map view matrix for a later project, if it is ever desired.

+1, I agree.

**Comment by manthey** [comment]
Added in PR #516.
