### ISSUE TITLE
Provide support for global view 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#446]
When zoomed in on a visualization, we want to have secondary view (overview) of the entire scene.

**Comment by jbeezley** [comment]
Requested for https://github.com/DigitalSlideArchive/HistomicsTK/issues/210

**Comment by manthey** [comment]
There are a number of options that could be present for the small image (all of these exist in other products):
- how the view of the large map is shown (the color of a rectangle or dimming outside the area, or other choices).  Ideally we make this css so it can be restyled easily.
- Must the two maps be in the same projection?
- Is the small map always the entire scene, or does it zoom to some extent at very high magnifications?  If it doesn't zoom and you are zoomed in far enough, the representation of the view area may be too small to be useful.
- Does the overview map rotate when the main map rotates, or does it stay at a fixed rotation?
- What controls are allowed on the small map?  Just clicking to pick the ROI?  Zoom/unzoom via wheel and/or area drag?  Dragging the selected area?  Rotation?  Should these all be adjustable, or should we make some defacto choices for now and make them adjustable when later desired?
- Does the overview map show features shown on the main map?

Opinions desired.

**Comment by manthey** [comment]
Closing this, since clients can do so as they see fit (see large_image as an example).
