### ISSUE TITLE
Add a method on `map` to reorder layers

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#452]
See #451.

Possible interface:
* Using a permutation array `map.layerOrder([0, 3, 1, 2])`, where the numbers are the indices of layer in `map.layers()`.
* `map.layerOrder()` returns the current permutation array.
* Using a compare function  `map.layerOrder(function (layer1, layer2) {...})` à la [`Array.prototype.sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)

**Comment by jeffbaumes** [comment]
I am unclear what `map.layerOrder()` would return - wouldn't it always be an array `[0, 1, 2, 3, ..., N-1]`? If not, that means there is some internal permutation state that the user needs to be aware of which seems overly burdensome to maintain and understand. I would expect the internal list of layers is directly modified instead of having a separate permutation. So I'd vote against the second bullet, and question the value of the first bullet.

**Comment by jbeezley** [comment]
Thats the complication I brought up in #451. What I'm proposing is that what is returned by `map.children()` would only change by adding or removing a layer.  The display order would be decided solely by the `z-index` property.  The return value of `map.layerOrder()` would be computed on demand.

Ex the defaults would look like this:
```python
>>> map.children()
[{id: 0, 'z-index': 0}, {id: 1, 'z-index': 1}, {id: 2, 'z-index': 2}]
>>> map.layerOrder()
[0, 1, 2]
```

Then reordering:
```python
>>> map.children()[1].moveUp()
>>> map.children()
[{id: 0, 'z-index': 0}, {id: 1, 'z-index': 2}, {id: 2, 'z-index': 1}]
>>> map.layerOrder()
[0, 2, 1]

>>> map.children()[1].moveDown()
>>> map.children()
[{id: 0, 'z-index': 0}, {id: 1, 'z-index': 1}, {id: 2, 'z-index': 2}]
>>> map.layerOrder()
[0, 1, 2]

>>> map.children()[0].moveUp(2)
>>> map.children()
[{id: 0, 'z-index': 2}, {id: 1, 'z-index': 0}, {id: 2, 'z-index': 1}]
>>> map.layerOrder()
[2, 0, 1]
```
etc.

I am open to changing these semantics if it is too confusing.  One reason, I don't want to have the display order determined by the place in the `children` array is because it uses the css z-index, which could change independent of the geojs api.  Also, I have been using the convention in a few applications where I'm storing the index of the layer as a kind of serialization so that I get it back by `map.children()[iLayer]`.

One idea I've had for a while is to allow naming layers so that `map.layers()` would return an object mapping layer names to layer objects.  This would certainly help confusion because an object would imply no ordering.

**Comment by jeffbaumes** [comment]
Ah, ok. Thinking a bit more, I think if there is direct z-index setting capability, permutation ordering (i.e. what this issue is all about) seems like it may not be a great idea in general, since the two modes of ordering could conflict with each other.

**Comment by jeffbaumes** [comment]
What I mean is: there is a consistent way to have both, but it's a different mental model.

**Comment by jbeezley** [comment]
I took convention when permuting to swap `z-index` values rather than try and do anything smarter.  So if you start with a set of z-indices `{0, 5, 100}`, `layerOrder` or `moveUp`/`moveDown` will always retain the same set.  Only a call to `layer.zIndex` will change it.  I had originally though about making `zIndex` protected, but I think there could be some legitimate public use cases.

**Comment by jbeezley** [comment]
Done in #451.
