### ISSUE TITLE
Use `npm prepublish` to bundle the release

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#462]
Putting a `grunt` build step in `postinstall` is a [bad idea](https://docs.npmjs.com/misc/scripts#best-practices) as it causes all sorts of [problems](https://github.com/npm/npm/issues/1341) due to npm's dependency resolution rules.  We should modify the release workflow to put the build step in `prepublish` instead so that built files are added to the npm release.  See also: https://goo.gl/R4HgaZ.

**Comment by aashish24** [comment]
+1
