### ISSUE TITLE
zoomAndCenterFromBounds doesn't take the projection into account

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#465]
When using zoomAndCenterFromBounds, the map doesn't necessarily end up with the specified bounds.  This is especially pronounced when using the common Mercator projection.  For instance, if the lower bound is the equator, and the upper bound is 60 degrees, the center is placed at 30 degrees, whereas it should be placed around 35 degrees 16 minutes.

For the same reason, the current extent and new extent should be calculated in the projected coordinates so as to ensure the correct change in zoom level.

**Comment by aashish24** [comment]
:bug: Are you going to push a fix for it @manthey ?

**Comment by manthey** [comment]
This is functionally fixed in PR #410, though it is only so because the default map and image projections are now in a space that has uniform units.  If we ever use an internal map projection that does't have that feature (or possibly when we add map rotation), this should be revisited then.
