### ISSUE TITLE
Share shaders among tiles in a tile layer

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#471]
Compiling the shaders per tile causes a large performance hit.  See the discussion in this thread: https://github.com/OpenGeoscience/geojs/pull/467#issuecomment-159061631.

**Comment by manthey** [comment]
I've submitted a PR in vgl that does this.

I think for ultimate performance, we will also want to share the GL program between tiles and reuse GL buffers and much as possible.

**Comment by jbeezley** [comment]
My main concern was the recompilation of the shader programs, which this appears to solve.  Thanks.

**Comment by aashish24** [comment]
@jbeezley will do the new release of vgl and bring it in geojs

**Comment by jbeezley** [comment]
Unfortunately, the changes in https://github.com/OpenGeoscience/vgl/pull/84 don't actually fix the problem.  When I looked at it a couple of weeks ago, I considered doing the same, but the `context` passed into [these methods](https://github.com/OpenGeoscience/vgl/blob/master/src/utils.js#L140) is just the global [`vgl.GL` object](https://github.com/OpenGeoscience/vgl/blob/master/src/utils.js#L486) rather than an actual GL context.  I think something more invasive will have to be done to pass the actual context in through the API.

**Comment by aashish24** [comment]
@jbeezley if we pass a different canvas element, it should have the global context. Look at the code here: https://github.com/OpenGeoscience/vgl/blob/master/src/renderWindow.js#L251

**Comment by aashish24** [comment]
I think this code has to changed
https://github.com/OpenGeoscience/geojs/blob/master/src/gl/vglRenderer.js#L78

**Comment by aashish24** [comment]
Sorry, I take it back. I am not sure why we are still getting a global context. I will have to look at in detail. The VGL test would not have worked with global context so may be something went wrong.

**Comment by aashish24** [comment]
@jbeezley the code you pointed need update. I will push a PR.

**Comment by manthey** [comment]
We get the global context because we are passing it from the construction
functions.  The actor isn't associated with the context until it is
attached to the contextRenderer.

I'm working on the issue.

On Tue, Jan 5, 2016 at 3:28 PM, Aashish Chaudhary <notifications@github.com>
wrote:

> Sorry, I take it back. I am not sure why we are still getting a global
> context. I will have to look at in detail. The VGL test would not have
> worked with global context so may be something went wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGeoscience/geojs/issues/471#issuecomment-169122568>
> .
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by aashish24** [comment]
@manthey cool.. I won't work on it then.

**Comment by jbeezley** [comment]
Another issue I just noticed when working with the vgl changes is a new bottleneck with the shaders.  It is most noticeable when `keepLower` is turned off.  The bottleneck occurs in [`shaderProgram.link`](https://github.com/OpenGeoscience/vgl/blob/master/src/shaderProgram.js#L235).  The time line for many interactions looks like this:
![screen shot 2016-01-06 at 1 30 59 pm](https://cloud.githubusercontent.com/assets/31890/12150801/dd342ffe-b479-11e5-8f92-a3bec258a6b8.png)

I'm wondering if there is a way to cache the result of this operation as well or if it needs to be tile specific.

**Comment by manthey** [comment]
That would require a bigger refactor, as it would involve reusing programs.

On Wed, Jan 6, 2016 at 1:34 PM, Jonathan Beezley <notifications@github.com>
wrote:

> Another issue I just noticed when working with the vgl changes is a new
> bottleneck with the shaders. It is most noticeable when keepLower is
> turned off. The bottleneck occurs in shaderProgram.link
> <https://github.com/OpenGeoscience/vgl/blob/master/src/shaderProgram.js#L235>.
> The time line for many interactions looks like this:
> [image: screen shot 2016-01-06 at 1 30 59 pm]
> <https://cloud.githubusercontent.com/assets/31890/12150801/dd342ffe-b479-11e5-8f92-a3bec258a6b8.png>
>
> I'm wondering if there is a way to cache the result of this operation as
> well or if it needs to be tile specific.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGeoscience/geojs/issues/471#issuecomment-169413038>
> .
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by aashish24** [comment]
> That would require a bigger refactor, as it would involve reusing programs.

@manthey lets talk about it today (you and me) this afternoon if possible.

**Comment by jbeezley** [comment]
With #497, I'll consider this issue closed.  I think further improvements can be opened in a new issue.
