### ISSUE TITLE
Implement a tile fetch queue

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#472]
Currently tile ajax requests are occurring on demand.  The browser allows only a small number of requests to occur simultaneously and internally keeps a queue of outstanding requests.  When a large number of tiles are requested during user interaction, tiles that are no longer relevant for the current view bounds block newer requests from being processed.  We should implement a custom queue that checks if the tile is still in bounds before issuing a request.  If it is not, it can be safely ignored.  Further optimization could possibly adjust the order of the queue so that more important tiles are prioritized.

**Comment by aashish24** [comment]
Charles and I discussed this and I believe he has some code. I request him to bring this code to geojs but I believe he has been busy or forgot about it. @manthey and I will look at this issue.

**Comment by manthey** [comment]
I have an implementation of this that I will submit shortly.  I still need to add some tests and check some of the code.

**Comment by aashish24** [comment]
great @manthey did you borrow code from slide atlas or this is a new implementation?

**Comment by manthey** [comment]
It is a new implementation that uses javascript promises (à la jquery).

**Comment by aashish24** [comment]
> It is a new implementation that uses javascript promises (à la jquery).

I see. Is there a reason, we should not look into what SlideAtlas has?

**Comment by manthey** [comment]
I did look.  I decided it would be faster to write code in the same style as what else we have in geojs than it would be to adapt the code in SlideAtlas.  Specifically, we use promises to handle a tile when the image is requested.  This allows individual components to not need to know about how things are being processed.  For instance, the imageTile object doesn't need to know anything about the fetch queue.  This will be a good thing when we handle vector tiles, as that class won't need to care about the queue either.

I've written a generic Deferred object fetch queue, so it could be reused for non-tiles if appropriate, too.

**Comment by aashish24** [comment]
> I did look. I decided it would be faster to write code in the same style as what else we have in geojs than it would be to adapt the code in SlideAtlas. Specifically, we use promises to handle a tile when the image is requested. This allows individual components to not need to know about how things are being processed. For instance, the imageTile object doesn't need to know anything about the fetch queue. This will be a good thing when we handle vector tiles, as that class won't need to care about the queue either.

Sure, faster is better :+1: but we should keep looking into slide-atlas code to bring it in geojs if possible and reasonable. Thanks for the update.

**Comment by manthey** [comment]
Added in PR #486.
