### ISSUE TITLE
Optimize `tileLayer._update`

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#473]
To reduce the code complexity during development of the recent refactor, the `tileLayer._update` method is over-aggressive in recomputing the visible tile set and rerendering.  It may help to throttle the rate at which this method is called similar to what is done with mouse events in #467, but most likely it will be necessary to keep a cache of tiles in for a larger viewport and only recompute the new tileset under certain conditions (pan or zoom by a certain amount, etc.).

**Comment by jbeezley** [comment]
When doing this we should keep track of the time spent in the update and ensure that no single call takes longer than 10ms.  Here are some nice resources about animation frame budget and debugging performance problems:

http://jankfree.org/
https://addyosmani.com/blog/performance-optimisation-with-timeline-profiles/

**Comment by manthey** [comment]
This has been vastly improved in PR #528.

Measuring and recording times will be addressed by issue #334, so I'm closing this issue.
