### ISSUE TITLE
Reduce memory allocations

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#474]
A big performance bottleneck in the current code are a result of many large garbage collections occurring during mouse events.  In the current code base, I see garbage collections that take 20-50ms occurring in about 1/2 of the map navigation invocations.  This accounts for about half of the time spent in the event handlers when no new tiles are rendered.  We should work to avoid allocation of temporary objects inside of event handlers and reduce the size of those objects that are.

Specific ideas to consider:

* Use prototypical inheritance via more modern conventions like `_.extend` rather than inside a constructor
* Use a lighter weight eventing system via some standard library
* Use native promises (with es5-promise as a shim)
* Don't generate plane features from tiles instead use a simpler class that isn't connected to the scene tree
* Keep references to "scratch spaces" on objects that are used inside methods rather than privately scoped objects that get reallocated on each call

**Comment by aashish24** [comment]
> Don't generate plane features from tiles instead use a simpler class that isn't connected to the scene tree

@jbeezley how does this affect the memory allocations? Could you please elaborate?

**Comment by jbeezley** [comment]
Here are some articles talking about minimizing garbage collection:

https://www.scirra.com/blog/76/how-to-write-low-garbage-real-time-javascript
http://www.html5rocks.com/en/tutorials/speed/static-mem-pools/
http://buildnewgames.com/garbage-collector-friendly-code/
http://blog.artillery.com/2012/10/browser-garbage-collection-and-framerate.html

**Comment by manthey** [comment]
This has been significantly improved via PR #528.  There is more that could be done, so I'll leave it up to @jbeezley if this is enough to close this issue or not.

**Comment by jbeezley** [comment]
We have a lot more that needs to be done in this direction, but I agree #528 took care of the low hanging fruit.  I'll go ahead an close this now and open a new more specific issues as we identify them.
