### ISSUE TITLE
Import leftover features from wigglemaps into GeoJS

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#477]
- [x] Import brushing functionality (specifically over point datasets)
- [x] Import polygon highlight feature
- [x] Import ascii grid reader feature

Ref: https://github.com/OpenGeoscience/geojs/issues/10

**Comment by jbeezley** [comment]
Brushing was added in #213.  Currently, it is handled for both points and lines.  Other features just need to implement the [`boxSearch`](https://github.com/OpenGeoscience/geojs/blob/c2746db327055359e1d2dab6d11b99740aa56d3a/src/core/pointFeature.js#L277) method to enable it.

**Comment by aashish24** [comment]
> Brushing was added in #213. Currently, it is handled for both points and lines. Other features just need to implement the boxSearch method to enable it.

@jbeezley thanks for bringing this up. You are right we do have this feature but what I would like is to provide a default handler that will highlight the points and lines that are brushed. So my updated wish list would be
- [ ] Provide default handlers for brushing and selection
- [ ] Implement box search for geometry feature 
- [ ] Import readers (yet to be determined)
