### ISSUE TITLE
Add more scientific dataset visualization examples using GeoJS

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#498]
@berkgeveci gave this nice suggestion.

**Comment by jbeezley** [comment]
Definitely a good idea.  I have wanted to replace the existing examples with real life cases for a while to be more in line with the hurricane example.  Perhaps we can use this issue to collect ideas about possible datasets and use cases to showcase.

**Comment by aashish24** [comment]
@jbeezley +1

Utkarsh and I was talking about El Niño today and it would be great if we can showcase the pattern in GeojS. Here is one of the story fron NASA web-site ( have another link which I will find and post). https://www.nasa.gov/feature/goddard/nasa-studying-2015-el-nino-event-as-never-before..

Also, would be nice to have some vector examples (earth quake, ocean, aos) etc.

**Comment by aashish24** [comment]
@dcjohnston have a look at the wind dataset here: 

http://windflow.azurewebsites.net/WindFlow39000L.html

I think vector feature for this dataset will be perfect.

**Comment by manthey** [comment]
@aashish24 This is currently an ill-defined issue.  How many examples are needed to satisfy it?  Can we close it with the recent addition of the rainfall example, or, if not, can we specify an explicit goal to reach?

**Comment by aashish24** [comment]
will put a more concrete request in the future.
