### ISSUE TITLE
Version 1.0 wishlist and planning

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#503]
We already have a milestone in place where we can place specific issues targeted for the 1.0 release.  What the milestone doesn't give is the ability to discuss more abstractly the goals for the release.  There has apparently been some questioning why I opposed marking the latest release as 1.0.  There are number of reasons why I would argue this, but the primary one is that this release is a major change from previous releases and the changes have not yet been battle tested by many users or applications.  There will almost certainly be problems that we will need to work out both internally and as API changes.  I would like to see more feedback of the community before marketing ourselves as stable.

A few other arguments I would make are some known deficiencies in the current state.  Here are a few:
* [Performance problems](https://github.com/OpenGeoscience/geojs/issues/474) due to using heavy weight closures for our class inheritance
* The feature API is [extremely inefficient](https://github.com/OpenGeoscience/geojs/issues/406) for dynamic datasets
* Over-reliance on selenium for testing (our phantomjs test coverage is still < 50%)
* Virtually no useable API documentation other than reading the docstrings in the source

The first two issues may very well require another round or two of major refactoring to get right.  The others are (in my humble opinion) basic prerequisites for a version 1.0.

**Comment by aashish24** [comment]
> Performance problems due to using heavy weight closures for our class inheritance
> The feature API is extremely inefficient for dynamic datasets
> Over-reliance on selenium for testing (our phantomjs test coverage is still < 50%)
> Virtually no useable API documentation other than reading the docstrings in the source

:+1: I have some more items but these are definitely some of the big ones.

**Comment by aashish24** [comment]
> Over-reliance on selenium for testing (our phantomjs test coverage is still < 50%)
> Virtually no useable API documentation other than reading the docstrings in the source

I think we covered these two in our milestone discussions today. The other two we haven't discussed as much. I would like to talk about it in our next sprint planning meeting.
