### ISSUE TITLE
Unexpected slow performance of geojs when loading geojson feature collection (points)

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#506]
@manthey I believe you had some idea. I will send you the data file in a separate email. I tested the data using geoJson example.

**Comment by jbeezley** [comment]
This is because you have 845 point features in the file, so the reader is creating 845 `geo.pointFeature` objects in the layer.  To fix it either convert the geojson to use a `MultiPoint` feature or use the `geo.pointFeature` directly.

**Comment by aashish24** [comment]
@jbeezley that's what I my thought as well looking at the data. I believe the conversion is happening inside minerva. @jbeezley can you look at the code and see if we can do a better job in creating the geojson? this is low priority compare to mmwr. 

@mgrauer @jeffbaumes

**Comment by aashish24** [comment]
@jbeezley actually let me work with @mgrauer on this.

**Comment by mgrauer** [comment]
We don't currently support mouse click interaction with points in Minerva--though @jeffbaumes asked me about it today--but are there related considerations?

I.e., if we want mouse interaction (click on a point and display related properties), would we be able to use the MultiPoint feature and still retain per-point properties?

**Comment by jbeezley** [comment]
Yes, in fact it would be much easier to use a single "multi" point feature for this purpose.

**Comment by aashish24** [comment]
> I.e., if we want mouse interaction (click on a point and display related properties), would we be able to use the MultiPoint feature and still retain per-point properties?

Yes, one thing I have not tested is how our reader handle other attributes (other than coordinates). I am pushing a fix for Minerva.
