### ISSUE TITLE
Use commonjs for dependency management

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#511]

**Comment by aashish24** [comment]
@jbeezley does your branch need something from @manthey on-going work?

**Comment by jbeezley** [comment]
I'm rebasing now.  It's still going to take a solid few days of work to finish up.

**Comment by aashish24** [comment]
> I'm rebasing now. It's still going to take a solid few days of work to finish up.

Sounds good @jbeezley
