### ISSUE TITLE
Share shader programs between tiles

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#517]
The [shaderProgram.link](https://github.com/OpenGeoscience/vgl/blob/master/src/shaderProgram.js#L235) method is causing performance problems.  See [this comment](https://github.com/OpenGeoscience/geojs/issues/471#issuecomment-169413038) for details.

**Comment by manthey** [comment]
I intend to resolve this as part of issue #228, which is next on my list of tasks.

**Comment by manthey** [comment]
Resolved in PR #528.
