### ISSUE TITLE
Map widgets example is not working

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#519]
The deployed version of the [map widgets example](http://opengeoscience.github.io/geojs/examples/widgets/) is no longer working.  I'm almost certain it was working at least on Chrome at the time of the 0.6.0 release.  I'm now using Chrome 47.0.2526.111.  I tried in current versions of every other major browser, and it is not working there either.

**Comment by manthey** [comment]
It works in Chrome 48.0.2564.82 m (64-bit), but not in Chrome 48.0.2564.97 m (64-bit).

**Comment by jbeezley** [comment]
All changes are breaking changes.

**Comment by manthey** [comment]
Fixed in PR #530.
