### ISSUE TITLE
GeoJS doesn't work in Opera

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#520]
Tested on version 12.15 build 1748.  There are numerous CSS related errors resulting in
```
Uncaught exception: Error: Invalid viewport dimensions
```
and no map is rendered.

**Comment by aashish24** [comment]
It would be good to fix it

**Comment by manthey** [comment]
It seems to work faultlessly on Opera of Windows version 35.0.2066.37.

**Comment by jbeezley** [comment]
Hmm... Somehow the version I installed a couple of months ago is ancient.  I have no idea how that happened.  It works in the current version.

**Comment by aashish24** [comment]
Did someone try opera on mobile devices?
