### ISSUE TITLE
Setup discussion call to review 1.0 milestone goals

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#523]
* What we want to get done for 1.0
* Review the current 1.0 milestone
* Discuss possible timeline

**Comment by manthey** [comment]
Isn't this the same as issue #503?

**Comment by aashish24** [comment]
I added this so that I can setup a time next week for discussions for the sprint

**Comment by aashish24** [comment]
Since we discussed 1.0 features/bugs/tasks, I am closing it now.
