### ISSUE TITLE
Prototype annotations using third party / or using existing feature in GeoJS

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#525]
- [ ] We need an example not necessarily an API
- [ ] We would like to go back (and forth) to edit the feature that drawn by the user in the first place
- [ ] The user-drawn features does not need to move/rotate for now if that simplifies things

**Comment by jbeezley** [comment]
I came up with a quick demo of using GeoJS with fabricjs in the manner that I described in [this comment](https://github.com/OpenGeoscience/geojs/issues/491#issuecomment-174019366).  It's committed as an example in the branch [annotation-demo](https://github.com/OpenGeoscience/geojs/tree/annotation-demo).  I also pushed it up  to jsbin as [http://jsbin.com/kediqir/4](http://jsbin.com/kediqir/4).  The code I used to implement it is very rough and there are a couple of bugs.

Some random impressions:
* Most of the complexity in the code is related to drawing the html and synchronizing between the state of the `button` and `input` elements and the map.
* Fabric does an excellent job of serialization and deserialization of its own state through methods like `canvas.toJSON` and `canvas.loadFromJSON`.  I was able to create geojs style objects that work with that serialization pretty easily.
* Fabric provides mouse handlers for the following operations: selection, dragging, rotation, and scaling.  We will need to maintain widgets to modify other attributes like color, line width, etc.
* Fabric can be [extended](http://fabricjs.com/fabric-intro-part-3/#subclassing) pretty easily.

My takeaway is that that majority of this code doesn't belong in GeoJS.  Instead, drawing and maintaining the widgets should be managed by the application's MVC framework.  If there is anything we can do in GeoJS, it should be to make integrating into an MVC framework less painful.  This means treating GeoJS as a "view" whose state can serialized in a manner similar to fabricjs.  It is relatively straightforward to serialize the state of point features as I have done in this example, but other features such as the polygon feature deserialize in complicated [nested loops](https://github.com/OpenGeoscience/geojs/blob/master/src/gl/polygonFeature.js#L113-L170), which need to be duplicated for each implementation of the feature.  I had the idea in an [abandoned PR](https://github.com/OpenGeoscience/geojs/pull/295) expose this deserialization as a method in each feature's base class.  To do this right, I think we need to revisit that idea in an overhaul of the feature API to support serialization and more efficient data binding (#406).

**Comment by aashish24** [comment]
@manthey @jbeezley should we close this as well?

**Comment by manthey** [comment]
I think so.
