### ISSUE TITLE
Increase coverage to 75% or more 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#534]

**Comment by aashish24** [comment]
Ref: https://github.com/OpenGeoscience/geojs/issues/329

**Comment by aashish24** [comment]
* We need to add test for planeFeature

**Comment by manthey** [comment]
I notice that we have a `clock` module which doesn't have tests.  It is instantiated with a map, but then we don't seem to do anything with it.  Obviously, some consumer of geojs might use it, but we could get rid of it before we release v1.0.

**Comment by aashish24** [comment]
> I notice that we have a clock module which doesn't have tests. It is instantiated with a map, but then we don't seem to do anything with it. Obviously, some consumer of geojs might use it, but we could get rid of it before we release v1.0.

I believe `clock` is used for animations which are time based. We had one example in the past.

**Comment by aashish24** [comment]
My preference would be to keep it, add an example and test unless the features provided by it are replaced by some other module.

**Comment by manthey** [comment]
You are right, the `dynamicData` example uses it.

**Comment by jbeezley** [comment]
There are integration tests for it in [d3Animation](https://github.com/OpenGeoscience/geojs/blob/master/testing/test-cases/selenium-tests/d3Animation/include.js).  The class itself was originally intended to be used for time synchronization in animations.

I don't think we've ever found a use for it in production, which IMO is a good metric for the usefulness of an API.  The 1.0 tag is a good opportunity to rethink API decisions that didn't pan out.

**Comment by aashish24** [comment]
> I don't think we've ever found a use for it in production, which IMO is a good metric for the usefulness of an API. The 1.0 tag is a good opportunity to rethink API decisions that didn't pan out.

+1

**Comment by aashish24** [comment]
@jbeezley @manthey should we close this since now we are > 90%?

**Comment by manthey** [comment]
We still have one source file that is essentially uncovered: the `ui/legendWidget.js` is only got 8% coverage.    I'd like to see it tested.

**Comment by aashish24** [comment]
> We still have one source file that is essentially uncovered: the ui/legendWidget.js is only got 8% coverage. I'd like to see it tested.

makes sense. Would it be @jbeezley that was planning to increase the coverage of legendWidget?

**Comment by aashish24** [comment]
@jbeezley @manthey I am thinking of closing this, we can create specific issues related to low coverage on certain files but feel free to re-open this if you think we should.
