### ISSUE TITLE
Implement a d3 rendered quad feature

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#540]
This should replace the `d3.planeFeature` in two places.
* The rectangle selection UI element in [mapInteractor](https://github.com/OpenGeoscience/geojs/blob/09484b857b866bea4acd28a8dc90cada177b29cf/src/core/mapInteractor.js#L659)
* The tiles in [d3.tileLayer](https://github.com/OpenGeoscience/geojs/blob/09484b857b866bea4acd28a8dc90cada177b29cf/src/d3/tileLayer.js#L13)

**Comment by manthey** [comment]
Added in PR #581.
