### ISSUE TITLE
Implement Grid Feature

### ISSUE THREAD

**Issue by dcjohnston** [OpenGeoscience/geojs#545]
Use examples from wigglemaps.

**Comment by aashish24** [comment]
@dcjohnston can you push your PR so that we @jbeezley @manthey could have a look at it?

**Comment by dcjohnston** [comment]
Sure thing, will push up by end of day.

**Comment by aashish24** [comment]
thanks @dcjohnston

**Comment by manthey** [comment]
An initial PR #614 was made for this.  Since that was made, an generalized grid class was introduced.  That PR could be revived if it were refactored to use the generalized grid class.
