### ISSUE TITLE
Performance improvements to canvas heatmap implementation

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#559]
Currently the heatmap implementation using canvas2D API does not scale and has very poor framerate even with smaller size datasets.

**Comment by aashish24** [comment]
From @jbeezley 

```
You can apply scale transform to simulate zooming. Yes, it is not the same thing as rerendering, but it makes for an acceptable visual substitute. The behavior that leaflet exhibits is that all animated navigations (zoom and pan) are simulated by CSS transforms. Once the animation is finished the debounced call to rerender the canvas is made.
```

**Comment by aashish24** [comment]
@jbeezley some other ideas:

* Render a coarser resolution (either at the data level or at the rendering level) - need to verify if this will really help (this is a very common vis technique). 

* Render only when user has stopped panning or zooming. (or combine it with css transformations) like @jbeezley suggested.

**Comment by manthey** [comment]
Added via PR #574 and #577.
