### ISSUE TITLE
Features don't wrap on map

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#569]
The heatmap should repeat appropriately when a map wraps in x or y.

**Comment by jbeezley** [comment]
AFAIK, none of the features (except tile layers) wrap appropriately.

**Comment by manthey** [comment]
Okay, I'll change this to "Features don't wrap on map".

**Comment by aashish24** [comment]
@manthey I was going to same as @jbeezley . There might be a performance penalty as well. I believe other similar tools don't wrap either but things may have changed lately.

**Comment by manthey** [comment]
This can be done manually by duplicating data with a 360 degree offset.  It won't be added by a core feature.
