### ISSUE TITLE
SVG transforms seem to be wonky on Chrome

### ISSUE THREAD

**Issue by ronichoudhury** [OpenGeoscience/geojs#575]
If you use the d3 renderer to plot some points on a map, then you zoom out and then pan, the dots will slide from their correct positions. It almost feels like a transform is being applied twice to the dots. If you don't zoom first, the problem doesn't appear. And this happens only on Chrome, so far as I can tell.

**Comment by ronichoudhury** [comment]
So, this seems to be affecting just the null renderer for the base layer, combined with the d3 renderer in a feature layer. When I instantiate my map with those settings, the bug appears both in Chrome and Firefox. :relieved:

I was getting the bug on Chrome because I don't have WebGL enabled, which causes the base layer to fall back on the null renderer, which in turn exhibits the problem.

**Comment by manthey** [comment]
@ronichoudhury If you are still set up to test this, can you try the canvas and d3 renderers for the osm layer (there are four renderers: `null`, `'canvas'`, `'d3'`, and `'vgl'`).

**Comment by ronichoudhury** [comment]
`'canvas'`, `'d3'`, and `'vgl'` all show the correct behavior. I confirmed again while I was at it that `null` does not.

**Comment by manthey** [comment]
Thank you.  I'll hunt down the bug.

**Comment by ronichoudhury** [comment]
Thanks!

**Comment by manthey** [comment]
This is only a problem with the `null` renderer's transform.  I've confirmed by having multiple osm layers overlapping -- the null renderer's layer migrates around compared to the other layers.

**Comment by manthey** [comment]
Fixed in PR #576.
