### ISSUE TITLE
Provide axes with ticks on geojs plots

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#591]
I have been thinking about this for some time. It would be nice if we have: 
1. X and Y axis with labels and ticks that respond to zoom in and out
2. Have a corresponding X-Y grid in gray color (with options to set color for it) that too changes with zoom  in and out. 
3. For full screen views, have ticks and labels on the right side of the axes (optional). Or have bit more flexibility on where to place labels. We could provide tons of options but for now I am thinking something simple. 

Thoughts?

**Comment by manthey** [comment]
I would think that for maps, the appropriate thing would be to have the grid according to some coordinate system (not necessarily the same as the map gcs or even the map interface gcs), and to show tick marks along the edges of the map (or grids across the map), with labels along either two or all edges.  This way, rotation would be handled somewhat sensibly.

For medical images, we would need to specify a scale, which might not be present anywhere else.

Different types of coordinate systems need different formatting and different logic to pick 'good' values.  For instance, for lat/lon, the format could be decimal degrees, degrees and decimal minutes, or degrees, minutes, and decimal seconds, each of which would 'snap' to good values differently.  For a state coordinate system, you probably are in meters or feet of easting and northing, with sensible changes to km or miles, etc.  For stereographic projections, you need radial grids (which would be tricky to determine automatically).

We could have a scale density, suggesting that a tick mark should appear roughly every _n_ pixels.

**Comment by aashish24** [comment]
> I would think that for maps, the appropriate thing would be to have the grid according to some coordinate system (not necessarily the same as the map gcs or even the map interface gcs),

+1. 

> nd to show tick marks along the edges of the map (or grids across the map), with labels along either two or all edges.

that's what I was thinking too. 

> Different types of coordinate systems need different formatting and different logic to pick 'good' values. For instance, for lat/lon, the format could be decimal degrees, degrees and decimal minutes, or degrees, minutes, and decimal seconds, each of which would 'snap' to good values differently. For a state coordinate system, you probably are in meters or feet of easting and northing, with sensible changes to km or miles, etc. For stereographic projections, you need radial grids (which would be tricky to determine automatically).

Right, we can start with something simple and leave room for improvements. Dealing with lat  / lon notation and float / int value is doable without too effort I would think.

**Comment by aashish24** [comment]
I am closing this issue as we didn't need this feature now but feel free to open it once relevant.
