### ISSUE TITLE
Line features in GL don't render correctly

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#596]
Wide lines at acute vertices appear to have the most trouble:

![image](https://cloud.githubusercontent.com/assets/8781639/16732788/d342abe0-474c-11e6-8c24-0c3f4d53c105.png)

**Comment by manthey** [comment]
There are two separate bugs here.

One is that some angles were miscalculated.  A fix for that is part of PR #597.

The second is the inside of acute angles.  If a line segment is short enough, the interior vertex of the intersection is badly placed.

**Comment by manthey** [comment]
Here is an image that shows a variety of line artifacts.  The blue lines are full-opacity lines with repeated junction points, while the grey lines are half-opacity lines without repeated junctions (i.e., if the grey line is [A, B, C, D], the blue line is [A, B, B, C, C, D]).

From left to right:
- Wide lines that overlap do not have constant opacity.  I don't see a way to fix this short of computing the bounding polygon for the line with width and then rendering it as a generic polygon.  We probably will just accept this as a limitation.
- Lines that exceed the miter limit don't render correctly.  We need more vertices to properly render a bevel join.  If we switch to generating the join normals during line vertex creation (as opposed to computing them in the vertex shader), we could generate an intermediate line segment or triangle when we exceed the miter limit.  Otherwise, we should at least detect this in the line vertex creation and pass a repeated vertex for the next or previous vertex.
- The center polyline is drawn correctly.
- This shows again the wide line overlap opacity issue.
- Lines that are wide, short, and joined at acute angles generate strange triangles.
 
![image](https://cloud.githubusercontent.com/assets/8781639/16958283/d7c94f0e-4dad-11e6-8097-dd6d4a8a2205.png)

**Comment by manthey** [comment]
In addressing this issue, we have the opportunity to also features to our lines.

Features we can add:
- Line cap style (butt, round, square)
- Line join style (miter, bevel, round, miter-clip)
- Miter limit (currently this isn't configurable)
- Stroke offset.  This could be simple, such as drawing the entire line to the center, left, or right, or it could be a float value that offsets the line anywhere between those locations.
- Antialiasing (the can be configurable in its magnitude).

Features that aren't being considered right now:
- Dashing
- Textured lines (these would be straightforward to add in the 2-D case).

Currently, we draw each line as a pair of triangles.  When we process the vertices in the vertex shader, we use three points and an offset for a total of 10 float values, plus the color (3 values), opacity, and line width, for a total of 15 float values per vertex.  This means that on graphics card that allows 1Gb of memory for attributes that we can draw 17.8 million line vertices, of 8.9 million line segments that aren't joined to others.

There are three technical approaches to fixing the errors we have and adding the features in the top list:

- (A) Make the geometry more involved that 2 triangles per segment.  This requires a fair amount of preprocessing, but has the virtue that the shaders are very simple.  It could be troublesome to make a general case that handles 3-D information efficiently.  If webGL 1.x supported geometry shaders, that could be used instead of preprocessing.

- (B) Preprocess information prior to generating our data to optimize for 2D lines.  Instead of including the next and previous vertices and computing angles in the vertex shader, compute angles in the preprocessing.  This makes extending to 3-D difficult, but reduces the time spend in the vertex shader and reduces the memory requirements from 15 to 11 floats per vertex.

- (C) Pass more information to the vertex shader so that the two triangles contain all necessary information for the various join conditions.  This has the virtue that 3D and perspective transforms can be done within the shaders, but will increase the memory from 15 to 18 floats per vertex.  It also makes the vertex shader more complex (but the preprocessing less so).

In thinking of how lines are requested, there are many varied conditions.  For instance, if a series of connected line segments have repeated vertices, (a - b - b - c - d - d - d - e), I think this should look identical to the same series of segments without repeated vertices (a - b - c - d - e).  Currently, if we have one repeated vertex, we handle it as if it wasn't repeated, but if we have multiple repeated vertices, we do odd things, such as treat them as a line segment of zero length that is oriented horizontally on the screen for purposes of mitering.  This applies to functionally repeated vertices (one that have the same x and y in the screen coordinates).

I'm currently considering option (B) to be the best compromise to handle repeated vertices, use less memory, and allow all of the options we care about.

Thoughts and opinions welcome.

**Comment by jeffbaumes** [comment]
Have you looked at this library?

https://github.com/mattdesl/extrude-polyline

**Comment by jbeezley** [comment]
Also worth considering is how mapbox-gl does it because they already do dashing, textured lines, 3D, and antialiasing efficiently enough to support vector tiling.  For reference, the preprocessing is done [here](https://github.com/mapbox/mapbox-gl-js/blob/3f1b490f0406a9bf9a7a795b685f981a9225e032/js/render/draw_line.js) and the shader code is in a different repo [here](https://github.com/mapbox/mapbox-gl-shaders/tree/master/src).

**Comment by aashish24** [comment]
Option B is fine and I believe that's what mapbox does, however, the parallel processing of vertex shader might be faster in certain cases. The limitation there would be is that you won't get any additional vertices in WebGL 1.x so in that sense B is the way to go. It would be interesting to see the timing differences just with that change if possible. I think in general B will provide most flexibility for the options we talked about with different joints. I have looked at the mapbox gl code before and I think it would be worth picking some ideas from it.

**Comment by jbeezley** [comment]
Also worth noting is that mapbox performs much (if not all) preprocessing in WebWorkers to achieve the performance necessary for tiling.  I suspect we will hit bottlenecks with this unless we go down a similar route.

**Comment by aashish24** [comment]
> https://github.com/mattdesl/extrude-polyline

This library looks interesting but seems to have inconsistent stroke widths on the corners; also the overlapping lines seems bit odd but it would be worth looking into it since it is using GL as well.

**Comment by aashish24** [comment]
> Also worth noting is that mapbox performs much (if not all) preprocessing in WebWorkers to achieve the performance necessary for tiling. I suspect we will hit bottlenecks with this unless we go down a similar route.

+1, performance was my concern with too much work on JS side of things with webworkers. Should we look into using webworkes? Or would it be a post 1.0 thing?

**Comment by jbeezley** [comment]
Making everything compatible with WebWorkers would take quite a lot of refactoring and make a significant departure from the current API.  If it went in after 1.0, it would most likely warrant a 2.0 release.

**Comment by aashish24** [comment]
> Making everything compatible with WebWorkers would take quite a lot of refactoring and make a significant departure from the current API. If it went in after 1.0, it would most likely warrant a 2.0 release.

+1, I agree

@manthey I guess in that case you may want to try out both B) and C) and see what works better in our current system. I would think B will provide most flexibility but may cost us performance and C) will probably give better performance but at the cost of more memory. I think memory would be less concern for me right now.

**Comment by manthey** [comment]
Fixed in PR #649.
