### ISSUE TITLE
Add API for setting named tile sets

### ISSUE THREAD

**Issue by jeffbaumes** [OpenGeoscience/geojs#60]
Like openstreetmaps, mapquest, etc.

**Comment by aashish24** [comment]
@jeffbaumes @manthey can we close this issue now?

**Comment by manthey** [comment]
Currently, you have to set the tile url as the whole string (e.g., `http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`).  I think this was proposing setting a dictionary of these values: `tiles = {osm: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'stamen-toner-lite': 'http://tile.stamen.com/toner-lite/{z}/{x}/{y}.png'}` and then supporting setting the tile url as a single word: `layer.url('osm')`.

This would make it convenient to specify a few tile sources quickly; we default to OSM, but if we wanted to have a short list of common tile servers, this would facilitate it.

**Comment by aashish24** [comment]
I see I thought it was this http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png but perhaps @jeffbaumes can confirm and most likely you are correct.
