### ISSUE TITLE
Configurable zoom slider

### ISSUE THREAD

**Issue by dorukozturk** [OpenGeoscience/geojs#618]
@jbeezley @manthey The zoom slider defaults to upper left corner. It would be great if widgets take a position argument so that you can put them on lower left or upper right.
Example: 
http://opengeoscience.github.io/geojs/examples/widgets/docs/main.html

**Comment by manthey** [comment]
Specifically, the zoom slider *ignores* the position argument.  I'll submit a PR with a quick fix shortly.

**Comment by manthey** [comment]
Resolved in PR #619.
