### ISSUE TITLE
Point clustering flickers when transitioning between zoom levels

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#620]
My first thought was that it was related to mouse wheel events quickly transitioning just above and below an integer in [this code](https://github.com/OpenGeoscience/geojs/blob/master/src/pointFeature.js#L113) but some quick debugging seems to indicate it is occurring in the rendering code.

<https://jsbin.com/fuleki/edit?js,output>

**Comment by aashish24** [comment]
I can see the flicker on my linux and and my mac consistently. @manthey are you going to have a look at it?

**Comment by manthey** [comment]
The flicker isn't caused directly by the zoom.  I'm working on hunting it down.

**Comment by manthey** [comment]
Try this out to see if it resolves the issue on your machines:

https://jsbin.com/tuyiparofu/edit?js,output

Note that PR #621 is functionally the same changes, but based on current master instead of that latest release.

**Comment by manthey** [comment]
Resolved by PR #621.
