### ISSUE TITLE
Consistent meaning of annotation events across annotation types

### ISSUE THREAD

**Issue by kotfic** [OpenGeoscience/geojs#623]
This [code path](https://github.com/OpenGeoscience/geojs/blob/master/src/annotationLayer.js#L327-L337) leads to inconsistent behavior for rectangle and point/polygon `geo.event.annotation.add` and `geo.event.annotation.state` events.  Point and polygon objects will trigger an add  on `layer.mode(...)` before any coordinates have been set. This information only becomes available for points and polygons in the state event. Rectangles on the other hand provide coordinate information in the add event,  and do not fire the state event at all.

**Comment by aashish24** [comment]
@manthey thoughts?

**Comment by manthey** [comment]
I see @kotfic's point, but I'm not completely convinced things should be changed.  Our choice is:

- Make it so any time you set the annotation layer mode a new annotation is created in the create state.  This requires all annotations to have a create state.  It is a pretty easy change, and unifies some of the behavior, but it isn't a technical necessity.

- Leave things as they are.  Some annotations have a create step and some don't.  Those with a create step issue a state change when then switch from create to done.  Those without a create step issue an add event when they are instantiated (and start in the done state).

- We could even change the point annotation so it doesn't have a create step, as it isn't required.

I'm leaning toward making all annotations have a create state.

**Comment by kotfic** [comment]
@manthey  this is your barbecue. I will say, as a user of the API,  I am actually less interested in the state of the annotation per-say and more interested in getting consistent events that I can hook into. I am especially interested in events that allow me to dynamically modify annotations attributes before the annotation is actually rendered.

**Comment by manthey** [comment]
Resolved in PR #643.  Ping @kotfic.
