### ISSUE TITLE
Enable users to modify / edit annotations via mouse 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#630]

**Comment by manthey** [comment]
As per a discussion, once an annotation is in edit mode, it will change its appearance and have several handles that indicate where a user can drag and manipulate it.  For our currently defined annotations:
- point:
  - the point itself is the handle and allows repositioning the point point
- rectangle
  - corner handles: change the position of the two adjacent sides (resize the rectangle)
  - edge handles: change the position of one side
  - center handle: reposition the rectangle
  - outside handle: rotate the rectangle
- polygon:
  - vertex handles: change the position of the vertex, altering the two adjacent edges.  If one vertex is dragged on top of another vertex, it will delete the vertex that has been dragged
  - edge handles: when dragged, create a new vertex and divide the side into two edges
  - centroid handle: reposition the polygon
  - outside handle: rotate the polygon
- line:
  - vertex handles: change the position of the vertex, altering the two adjacent edges.  If one vertex is dragged on top of another vertex, it will delete the vertex that has been dragged.  If the line is not closed and the first and last vertices are made coincident, this should close the line (though there might need to be a way to suppress this)
  - edge handles: when dragged, create a new vertex and divide the side into two edges
  - centroid handle: reposition the line
  - outside handle: rotate the line
  - ? the may need to be some way to break a closed line.

Initially the handles will just be shown as point features.  In the future we may want them to be fancier.  If a manipulation mode is not allowed, the associated handle shouldn't appear (for instance, rotation may not be allowed).

Selecting annotations for editing and turning off edit mode could be the first steps in implementing edit.

Eventually we would like to be able to focus a specific handle and control it via the keyboard, but that can be added after mouse controls.

**Comment by manthey** [comment]
Added in PR #769.
