### ISSUE TITLE
On ubuntu 14.04 the examples tests are timing out

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#659]
npm run test-examples

So far, this happens only on my system, docker is fine, so somehow it is environment related. 

webpack: bundle is now VALID.
10 01 2017 14:43:46.876:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
10 01 2017 14:43:46.895:INFO [launcher]: Starting browser Firefox
10 01 2017 14:43:51.925:INFO [Firefox 50.0.0 (Linux 0.0.0)]: Connected on socket 7aHBtvTle1ojE1oAAAAA with id 623429
Firefox 50.0.0 (Linux 0.0.0) lines example basic FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. in /home/chaudhary/tools/geojs/geojs.git/node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 1973)
	attemptAsync/timeoutId<@/home/chaudhary/tools/geojs/geojs.git/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1973:23
Firefox 50.0.0 (Linux 0.0.0): Executed 1 of 3 (1 FAILED) (0 secs / 10.374 secs)
Image comparison: exampleLines, delta: 0.1954

**Comment by manthey** [comment]
Try this dockerfile to see how it works: https://gist.github.com/manthey/20aab13a46485f5fbf721e179aa7cdcc

**Comment by manthey** [comment]
I believe this has been addressed with some tweaks to timing tests as part of PR #677.  Please open a new issue if needed.
