### ISSUE TITLE
Add support for KML format

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#67]

**Comment by manthey** [comment]
@aashish24 We should either close this issue or rename it to not involve wigglemaps.  Do you recall who wanted to use KML format?

**Comment by aashish24** [comment]
I believe it was a project at the time and they had the KML format. This is a whileback so I do not remember the details (perhaps I can find out). But I know that Bob's project was producing KML and around this time we develop a google earth view to visualize it. I think it is a pretty common practice that folks produce KML for demo purposes. Although I would not put this as a priority. There might be a better format now but I have not looked for it. WiggleMaps had a simple  KML reader but since we remove WiggleMaps we can probably change the title.

**Comment by aashish24** [comment]
I am no longer enthusiastic about KML since google earth API is deprecated and no one has asked for KML in a long time (not only in geojs). Closing it now but please feel free to open if someone thinks we need this feature.
