### ISSUE TITLE
Update to use pugjs instead of Jade which is deprecated for a while

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#678]
@jbeezley any thoughts?

**Comment by manthey** [comment]
We switched to pug on Girder without much difficulty.  Pug is still listed as in beta (https://www.npmjs.com/package/pug - currently `2.0.0-beta11`), though.

**Comment by aashish24** [comment]
Roger that @manthey I will push a PR to switch to pug soon.

**Comment by manthey** [comment]
Resolved in PR #722.
