### ISSUE TITLE
Demo WMS server used in examples is down

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#690]
We are using an external WMS server for the following two examples:
1. http://opengeoscience.github.io/geojs/examples/sld/
2. http://opengeoscience.github.io/geojs/examples/wms/

According to http://demo.geohealthcheck.org/resource/17, it has been down for at least a month.  Should we remove the examples?  Is there a different server we can use?

**Comment by aashish24** [comment]
perhaps we can use the wms server from massgis: We can find few examples here: https://wiki.state.ma.us/display/massgis/GeoServer+-+SLD+-+Polygon+Example+as+Points

**Comment by jbeezley** [comment]
It looks like it's back up.

**Comment by manthey** [comment]
The server we've been using has gone up and down.  It now reports CORS errors.

We need to find a server that is public and supports something interesting for sld requests.

**Comment by manthey** [comment]
This was corrected by switching to https.
