### ISSUE TITLE
Prevent selecting html elements when dragging

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#691]
We need to call preventDefault when interacting so that arbitrary text is not highlighted by drags.

**Comment by manthey** [comment]
We have `user-select: none` as a css property on the map (added in 0.12).  @jbeezley is this sufficient, or should we also call `preventDefault`?

**Comment by jbeezley** [comment]
`user-select` on the map element isn't sufficient to prevent selection on elements outside the map.  You have to prevent the default mouse move behavior as well.

**Comment by manthey** [comment]
I can't figure out how to reproduce the undesired behavior (as far as I can tell, I never highlight text during a drag, no matter where it is located).

**Comment by jbeezley** [comment]
I can no longer reproduce it either.
