### ISSUE TITLE
Event property type is not used consistently

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#703]
In `src/events.js`'s documentation, we claim that all events have a property called `type` which contains the string that identifies the event.  However, in `src/object.js`, we store the event identifier in the event object's `event` property.  We *also* use the `type` property on a handful of events from `map.js`: `layerAdd`, `layerRemove`, `resize`, `draw`, `drawEnd`.

I think we should remove the `type` property, but that would be a breaking change.  Alternately, we could assign the event identifier to *both* the `event` and `type` properties.

**Comment by aashish24** [comment]
I am in favor for removing the type as type and event could confuse the end-user. Since we do not have 1.0 I think it I would be okay with the breaking change. Also event is more connecting than type.

**Comment by manthey** [comment]
I had already made the decision to remove most of the `type` references.  PR #718 finishes the job.
