### ISSUE TITLE
BoxSearch is broken

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#705]
We have methods for performing box searches on point and line features.  However, the feature functions pass coordinates in the map's gcs coordinate system (usually web Mercator), and the box search functions check in interface gcs (usually latitude and longitude).  Furthermore, the box search is done just using opposite corners, so it *won't* work properly on a rotated map, even if the interface and display coordinate systems are the same.

**Comment by manthey** [comment]
When we fix this, I recommend changing the output of `boxSearch` functions to match that of `pointSeach`.

**Comment by aashish24** [comment]
@jbeezley would you like to take care of this bug?
