### ISSUE TITLE
Release v0.13 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#726]
@jbeezley would it be possible to schedule it this week or early next week? Before Foss4g? 

Also, having a external blog would be nice @manthey discussing the release and annotation with text feature.

**Comment by aashish24** [comment]
@jbeezley just found out that v0.12.3 is not on npm. Also, when you get a chance can you release+push 0.13 on npm? I am using v0.12.2 as of now which is fine but prefer to use the latest if possible.

**Comment by jbeezley** [comment]
I published v0.12.3 this morning.  I don't think there's anything new yet for 0.13.

**Comment by manthey** [comment]
Version 0.13 was published in November.
