### ISSUE TITLE
Provide multi-color legend for numeric values 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#734]
Ref #733 #278 #714

**Comment by manthey** [comment]
Was this satisfied by PR #731?  If not, what is still needed?

**Comment by aashish24** [comment]
do we have the legend for continuous range? I think we talked about it for example: https://discourse-cdn-sjc2.com/standard16/uploads/plot/optimized/1X/d37be82bc9c153aa807b2d2fbec5ab1b824acb3f_1_690x483.PNG

**Comment by manthey** [comment]
Our example shows continuous ranges shaded between two colors: http://opengeoscience.github.io/geojs/examples/color-legend/

**Comment by aashish24** [comment]
duh! yes we can close this issue then.
