### ISSUE TITLE
Allow custom ordering determination mechanism when there are overlapping features

### ISSUE THREAD

**Issue by matthewma7** [OpenGeoscience/geojs#778]
Currently, when there are overlapping features, GeoJS will determine the ordering based on the internal z-index of the feature, the feature has higher z-index will have higher priority for events. 
Would request a functionality that allows a custom ordering determination mechanism, such as order by the distance of feature borders or centroids to the cursor.

![image](https://user-images.githubusercontent.com/3123478/36449173-0017b652-1658-11e8-97ec-a684b789b9f9.png)

**Comment by manthey** [comment]
Added in PR #807.
