### ISSUE TITLE
Documentation: Make lists of available options easier to find

### ISSUE THREAD

**Issue by wphicks** [OpenGeoscience/geojs#842]
There are several places in the API documentation where functions accept one of a few strings as an argument but where it is difficult to find what the allowed values of those strings are. As a specific example, in [the documentation for annotationLayer mode](http://opengeoscience.github.io/geojs/apidocs/geo.annotationLayer.html#mode), `arg` can specify "the name of the type of annotation to create," but there is no list of the available types of annotation.

**Comment by manthey** [comment]
In your referenced example, the modes are either the special case `<annotation layer>.modes.edit` or one of the `geo.listAnnotations()`.  While presently the core library has four annotations, at least one of the intents is that these could be extended by a user of geojs, in which case this would be a dynamic list.  I'll update this function's docs with this information, and we can make new issues for other points where something similar is needed.
