### ISSUE TITLE
Annotation layer geojson function removes points

### ISSUE THREAD

**Issue by wphicks** [OpenGeoscience/geojs#847]
Using the `geojson` function of an annotation layer multiple times with the same argument peels off points from the passed geojson object. That is to say, a feature that starts off as a rectangle becomes a triangle and so forth. This can be minimally reproduced with the following, adapted from the "osm" example. Note the two successive calls to `geojson` at the bottom.

```javascript
// Run after the DOM loads
$(function () {
  'use strict';

  // Create a map object
  var map = geo.map({
    node: '#map',
    center: {
      x: -98.0,
      y: 39.5
    },
    zoom: 3
  });

  // Add the osm layer with a custom tile url
  map.createLayer(
    'osm',
    {
      url: 'http://tile.stamen.com/toner-lite/{z}/{x}/{y}.png',
      attribution: ['Map tiles by <a href="http://stamen.com">Stamen Design</a>,',
        'under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>.',
        'Data by <a href="https://openstreetmap.org">OpenStreetMap</a>, under',
        '<a href="https://openstreetmap.org/copyright">ODbL</a>.'
      ].join(' ')
    }
  );
  var annotationLayer = map.createLayer('annotation');
  var newGeoJson = {
    "features": [
      {
        "geometry": {
          "coordinates": [
            [
              [
                -127.509765625,
                22.722843068750073
              ],
              [
                -127.509765625,
                38.17546626008757
              ],
              [
                -100.263671875,
                38.17546626008757
              ],
              [
                -100.263671875,
                22.722843068750073
              ],
              [
                -127.509765625,
                22.722843068750073
              ]
            ]
          ],
          "type": "Polygon"
        },
        "properties": {
          "annotationId": 1,
          "annotationType": "rectangle",
          "fill": true,
          "fillColor": "#00ff00",
          "fillOpacity": 0.25,
          "name": "Rectangle 1",
          "stroke": true,
          "strokeColor": "#000000",
          "strokeOpacity": 1,
          "strokeWidth": 3
        },
        "type": "Feature"
      }
    ],
    "type": "FeatureCollection"
  };
  annotationLayer.geojson(newGeoJson, true);
  annotationLayer.geojson(newGeoJson, true);
});
```

**Comment by manthey** [comment]
Internally, if the last point matches the first point of a polygon, it gets trimmed off of the list.

By definition geojson is a string.  If you pass geojson, the geojson is converted to objects and this is only done on the self-generated objects.

If you pass an object (as in the example above, for instance), then this can modify the coordinate array that is included.  GeoJS (for better or worse) assumes that it has ownership of the passed object.  We could change this by using slice rather than splice the coordinate array, which would use more memory.

**Comment by wphicks** [comment]
I'm not too surprised about assuming ownership, but it looks like the test for matching first and last points is doing something unexpected here. If you run this, you'll see that a triangle is displayed, so we're getting two trims. The first (correctly) trims the matching last point, but in the next geojson call, the first and last points definitely shouldn't match.

**Comment by wphicks** [comment]
One other thought with respect to passing geojson solely as a string: We might think a bit about documentation or function-naming here. It probably makes sense that a call to `geojson()` returns an object, since a user will want to manipulate that object, but I would also expect that `geojson(args)` should accept arguments in the same format as `geojson()` outputs.
