### ISSUE TITLE
Documentation: Make it easier to find styling options for features

### ISSUE THREAD

**Issue by wphicks** [OpenGeoscience/geojs#857]
It would be helpful to make it easier to find available styling options for features. As a specific example, if I look at the [documentation for polygonFeature](http://opengeoscience.github.io/geojs/apidocs/geo.polygonFeature.html#style), I don't see what style options are available for polygons.

**Comment by manthey** [comment]
Some of this was improved in PR #819, so at least the styles are enumerated in the [geo.polygonFeature.spec](http://opengeoscience.github.io/geojs/apidocs/geo.polygonFeature.html#.spec), though this hasn't been published to github.io yet.

For polygons (and features that subclass the `style` function), we could put a link to the appropriate typedef (or, less optimally, duplicate the docs from that typedef).  For features where the `style` function is inherited, this wouldn't be directly possible. 

@wphicks, do you think a link to the appropriate typedef is sufficient, or do you think that duplicating the documentation would be preferred?
