### ISSUE TITLE
geoOn and selectionAPI

### ISSUE THREAD

**Issue by jeffbaumes** [OpenGeoscience/geojs#871]
In my couple of times using GeoJS, I've run into this issue where I've needed to rediscover that you need to turn on the `selectionAPI` option in order for mouse events to function. I have a few suggestions:

* Make a better name for `selectionAPI` that indicates that it allows interaction.
* If `selectionAPI` is turned off, emit an warning/error/exception when attempting to perform `geoOn()` with an event that will not function. Currently it silently lets you call `geoOn()` but then does nothing.

**Comment by johnkit** [comment]
+1

**Comment by waxlamp** [comment]
Ran into this myself when creating a new GeoJS application.
