### ISSUE TITLE
Rename renderers

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/geojs#898]
The `d3` renderer doesn't actually require d3, and would more properly be called the `svg` renderer.  As part of renaming it, remove any dependencies that do exist on d3 (some features will still require d3, such as the color legend).

Do we also want to rename the `vgl` renderer to `webgl` or just `gl`?

**Comment by manthey** [comment]
@aashish24 Can you weigh in on whether we should rename the `vgl` renderer, and, if so, what it should be renamed to?

As part of renaming renderers, I propose we rename the src directories associated with them, too.

**Comment by manthey** [comment]
As a related topic, the `dom` renderer might alternately be called the `ui` renderer.  Within the `dom` renderer, we call things widgets.  For all other renderers, we call things features.  Should this terminology be changed (should everything be a feature, for instance)?  If we should change the terminology, we can do so in a separate issue.

**Comment by aashish24** [comment]
rename to webgl
