### ISSUE TITLE
whether geojs support draw counter line on mapbox layer?

### ISSUE THREAD

**Issue by petitlen** [OpenGeoscience/geojs#992]
whether geojs support draw counter line on mapbox layer?

**Comment by manthey** [comment]
Do you mean isolines, like in this example: http://opengeoscience.github.io/geojs/examples/isoline/, or shaded contour plots like this: http://opengeoscience.github.io/geojs/examples/contour/, or something else?

Also, mapbox is a different program; you can use geojs as a layer above or below other renderer's layers, though you have to write some code to keep the map coordinates synchronized between the two.

**Comment by manthey** [comment]
Closing this without more specifics.
